version: '3.3'
services:
  api:
    build:
      context: .
      cache_from:
      - &img_tag telegram-telegram-standup-bot
    image: *img_tag
    depends_on:
      - mongodb
    restart: on-failure
    volumes:
      - .:/app
      - /var/standup:/data
  mongodb:
    image: mongo
    restart: on-failure
    volumes:
    - ./mongo:/data/db
  logger_api:
    build:
      context: telegram-standup-logger
      cache_from:
        - &logger_tag telegram-telegram-standup-logger
    image: *logger_tag
    depends_on:
      - mongodb
    restart: on-failure
    ports:
      - "8999:8000"
    volumes:
      - ./telegram-standup-logger:/app
  logger_viewer:
    build:
      context: telegram-standup-viewer
      cache_from:
        - &viewer_tag telegram-telegram-standup-viewer
    env_file:
      - viewer.env
    image: *viewer_tag
    depends_on:
      - logger_api
    restart: on-failure
    ports:
      - "8980:80"
